### ISSUE TITLE
SSL not run

### ISSUE THREAD

**Issue by XinYiMan** [groupsc10/RSQL#2]
Hi, I can't enable ssl encryption on data. Without a strong working encryption form this component becomes useless in production. Is there an example to do it?

**Comment by heliosroots** [comment]
You are confusing... ssl is one thing and jwt and another ... I added the example in the project and validated in "www.jwt.io" and it is working! If you want to protect the data you can use deflate or another algorithm !

**Comment by XinYiMan** [comment]
I am aware that they are two different things. In fact I had reported two different problems. One was the jwt you solved. The other was that in the
TRSQLHTTPServer1 there is the UseSSL property which I think serves to encrypt the connection so as not to transfer the queries in the clear over the network. I just can't get it to work. If you have examples of how to encrypt the traffic produced by TRSQLHTTPServer I am happy to analyze them

**Comment by heliosroots** [comment]
ssl is TFPCustomHttpServer inheritance...

**Comment by XinYiMan** [comment]
I modified the client so that you don't use {$ ifdef TRSQLHTTPConnectionUseSSL} but use the property Use_SSL. I enclose the code.

[rsql_client_connection.pas.zip](https://github.com/groupsc10/RSQL/files/3804469/rsql_client_connection.pas.zip)
